on:
  pull_request:
    # branches: [main]
  workflow_dispatch:

name: test vars

jobs:
  test-context-var:
    runs-on: ubuntu-latest
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    steps:

      - name: test context vars
        run: |
          cat("${{ github.event_name}}\n")
          cat("${{ github.run_id}}\n")
          cat("${{ github.event_name != 'pull_request' || github.run_id }}\n")
          cat("${{ github.base_ref }}\n")
        shell: Rscript {0}
